complete -c source-fish -s v -l version -f -d "Show version info"
complete -c source-fish -s h -l help -f -d "Show help"
complete -c source-fish -s r -l recent -f -d "Find recently modified files & source them"
complete -c source-fish -s a -l all -f -d "Source all fish files under the current directory"
complete -c source-fish -s t -l test -f -d "Source all fish files in the \"test\" folder"
complete -c source-fish -s c -l config -f -d "Source fish files in the config directory"